name: System Installer
description: Install ramOS to hard disk with EXT4 filesystem
version: 1.0.0
author: ramOS Development Team
category: System
binary: installer.elf
icon: install.ico
permissions:
  - console_io
  - disk_access
  - file_read
  - file_write
  - mount
  - admin
dependencies: []
build_time: "2025-10-05 15:20:30 UTC"
build_flags:
  - -O2
  - -fno-builtin
  - -nostdlib