name: Keyboard Layout Manager
description: Manage keyboard layouts and change active layout
version: 1.0.0
author: ramOS Development Team
category: System
binary: kbmap.elf
icon: keyboard.ico
permissions:
  - console_io
  - file_read
  - file_write
dependencies: []build_time: "2025-10-05 15:20:30 UTC"
build_time: "2025-10-05 15:47:56 UTC"
